name: dataUpdate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Collect and Analyze data
      run: |
        python dataAnalysis/macro/main.py
        python dataAnalysis/notebook/main.py

    - name: Commit and push changes
      run: |
        git add dataAnalysis/macro/data.json dataAnalysis/macro/excluded_list.txt
        git commit -m "Update data.json and excluded_list.txt"
        git push
