name: dataUpdate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy

    - name: Collect data
      run: |
        python dataAnalysis/macro/main.py

    - name: Commit and push macro data changes
      run: |
        git add dataAnalysis/macro/data.json dataAnalysis/excluded_list.txt
        git commit -m "Update macro data.json and excluded_list.txt"
        git push

    - name: Analyze data
      run: |
        python dataAnalysis/notebook/main.py

    - name: Commit and push notebook data changes
      run: |
        git add dataAnalysis/notebook/chart_data.json
        git commit -m "Update notebook data.json"
        git push
